server.port: 80
spring.redis.host: localhost
spring.redis.port: 6379
zuul:
  routes:
    auth:
      path: /auth/**
      url: http://localhost:7070
      sensitiveHeaders: 
    service:
      path: /service/**
      url: http://localhost:9090
      sensitiveHeaders: 